version: '3.8'
services:
  spring-app:
    build:
      context: .  # 프로젝트 루트에서 빌드
      dockerfile: Dockerfile
    image: lawmate-image:latest
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs  # 로그 파일 공유
