// ✅ 전체 수정사항 반영된 ChatbotPage.tsx

import React, { useState, useRef, useEffect } from 'react';
import ChatBubble from '@/components/chatbot/ChatBubble';
import ChatInput from '@/components/chatbot/ChatInput';
import {
  loadChatHistory,
  saveChatHistory,
  clearChatHistory,
  loadConsultationId,
  saveConsultationId,
} from '@/utils/chatStorage';
import { useNavigate } from 'react-router-dom';
import { startChat, continueChat, sendChatToBot } from '@/api/chat';
import { IS_USE_MOCK_API } from '@/routes/config';
import { extractAutoGenerateData } from '@/utils/parseAutoGenerate';
import { loadLocalReports, deleteLocalDoc } from '@/utils/localSavedDocs';

// ✅ 직접 정의된 템플릿 이름 매핑 (영문 코드 → 한글 표시명)
const templateNameMap: Record<string, string> = {
  CONTENT_PROOF: '내용증명',
  DEFAMATION_REPORT: '고소장(명예훼손)',
  PAYMENT_OBJECTION: '지급명령 이의신청서',
  LEASE_CONTRACT: '부동산 임대차 계약서',
  WILL_DOCUMENT: '유언장',
  EMPLOYMENT_CONTRACT: '근로계약서',
  LOAN_AGREEMENT: '금전차용증',
  OCR_ANALYZED: '업로드 문서',
};

export interface Message {
  sender: 'user' | 'bot';
  text: string;
  type?: 'text' | 'suggest';
  options?: string[];
  timestamp?: string;
}

const ChatbotPage: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(false);
  const [consultationId, setConsultationId] = useState<number | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const navigate = useNavigate();

  const getTime = () => new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  useEffect(() => {
    setMessages(loadChatHistory());
    setConsultationId(loadConsultationId());
  }, []);

  useEffect(() => {
    const filtered = messages.filter((msg) => msg.text !== '__typing__');
    if (filtered.length > 0) saveChatHistory(filtered);
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSaveSummaryToDB = async (
    consultationId: number,
    summary: string,
    issue: string,
    templateId: number
  ) => {
    try {
      const token = localStorage.getItem('token');
      if (!token) {
        console.warn('❗ 저장 실패: 로그인 토큰이 없습니다.');
        return;
      }

      const res = await fetch(`/api/consult/StartDocument/${consultationId}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ summary, issue, templateId }),
      });

      if (!res.ok) {
        const errorText = await res.text();
        throw new Error(`요약 저장 실패 (status ${res.status}): ${errorText}`);
      }

      console.log('✅ 요약 저장 완료');
    } catch (e) {
      console.error('❗ 요약 저장 중 오류:', e);
    }
  };

  const typeBotReply = async (text: string) => {
    const delay = (ms: number) => new Promise((res) => setTimeout(res, ms));
    let typed = '';
    for (let i = 0; i < text.length; i++) {
      typed += text[i];
      setMessages((prev) => {
        const updated = [...prev.slice(0, -1), { sender: 'bot', text: typed, timestamp: getTime() }];
        saveChatHistory(updated.filter((msg) => msg.text !== '__typing__'));
        return updated;
      });
      await delay(20);
    }
  };

  const handleSend = async (input: string) => {
    if (!input.trim() || loading) return;

    const userMsg: Message = { sender: 'user', text: input, timestamp: getTime() };
    const nextMessages = [...messages, userMsg];
    saveChatHistory(nextMessages);
    setMessages([...nextMessages, { sender: 'bot', text: '__typing__', timestamp: getTime() }]);
    setLoading(true);

    try {
      if (input.includes('저장된 문서') || input.includes('저장한 문서') || input.includes('문서 확인')) {
        const savedReports = loadLocalReports();
        if (savedReports.length === 0) {
          setMessages((prev) => [...prev.filter((m) => m.text !== '__typing__'), {
            sender: 'bot', text: '📂 저장된 문서가 없습니다.', timestamp: getTime()
          }]);
        } else {
          const buttons = savedReports.map((r) => {
            const name = templateNameMap[r.templateType] ?? r.templateType;
            return {
              label: `📄 ${name} (${r.savedAt})`,
              savedAt: r.savedAt,
            };
          });

          setMessages((prev) => [
            ...prev.filter((m) => m.text !== '__typing__'),
            {
              sender: 'bot',
              text: '🗂 저장된 문서 내역입니다.',
              type: 'suggest',
              options: buttons,
              timestamp: getTime(),
            },
          ]);
        }
        setLoading(false);
        return;
      }

      let answer = '';
      if (IS_USE_MOCK_API) {
        const res = await sendChatToBot(input);
        answer = res.answer;
      } else {
        let response;
        if (consultationId === null) {
          response = await startChat(input);
          setConsultationId(response.consultationId);
          saveConsultationId(response.consultationId);
        } else {
          const messagesToSend = nextMessages.map((m) => ({
            role: m.sender === 'user' ? 'user' : 'assistant',
            content: m.text,
          }));
          messagesToSend.push({ role: 'user', content: input });
          response = await continueChat(consultationId, messagesToSend);
        }
        answer = response.message || '응답을 받아올 수 없습니다.';

        if (answer.includes('문서 작성 모드로 전환합니다')) {
          const jsonMatch = answer.match(/```json\n([\s\S]+?)```/);
          if (jsonMatch && consultationId) {
            try {
              const parsed = JSON.parse(jsonMatch[1]);
              const summary = JSON.stringify(parsed, null, 2);
              const issue = parsed.제목 || parsed.고소_이유 || parsed.이의_사유 || '이슈 없음';
              await handleSaveSummaryToDB(consultationId, summary, issue, 1);
            } catch (e) {
              console.warn('❗ JSON 파싱 실패:', e);
            }
          }
        }
      }

      setMessages((prev) => [...prev.filter((m) => m.text !== '__typing__'), {
        sender: 'bot', text: '__typing__', timestamp: getTime()
      }]);
      await typeBotReply(answer);
    } catch (e) {
      console.error(e);
      setMessages((prev) => [...prev.filter((m) => m.text !== '__typing__'), {
        sender: 'bot', text: '❗ 오류가 발생했습니다. 다시 시도해주세요.', timestamp: getTime()
      }]);
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    clearChatHistory();
    setMessages([]);
    setConsultationId(null);
  };

  const handleShowJsonDocument = async () => {
    if (!consultationId) {
      alert('먼저 대화를 시작하고 문서가 생성된 상태여야 합니다.');
      return;
    }
    try {
      const res = await fetch(`/api/document/json/${consultationId}`, {
        headers: { Authorization: `Bearer ${localStorage.getItem('token')}` },
      });
      if (!res.ok) throw new Error('문서를 찾을 수 없습니다.');
      const json = await res.text();
      alert(`✅ 자동 생성된 문서 요약:\n\n${json}`);
    } catch (err) {
      alert(`❗ 문서 조회 실패: ${err}`);
    }
  };

  const handleSelectSuggestion = (option: string) => {
    if (option.startsWith('📄')) {
      const savedReports = loadLocalReports();
      const matched = savedReports.find((r) => {
        const name = templateNameMap[r.templateType] ?? r.templateType;
        return option.includes(name) && option.includes(r.savedAt);
      });

      if (matched) {
        navigate('/edit', {
          state: {
            templateType: matched.templateType,
            content: matched.content,
            analysisSummary: matched.analysisSummary ?? '',
            clauses: matched.clauses ?? [],
          }
        });
      }

    } else if (option === '문서 작성하기') {
      navigate('/edit');
    } else if (option === '자동 생성된 문서 확인하기') {
      handleShowJsonDocument();
    } else {
      handleSend(option);
    }
  };


  const lastBotMessage = messages.filter((msg) => msg.sender === 'bot' && msg.text && msg.text !== '__typing__').slice(-1)[0];
  const autoGenerateData = lastBotMessage ? extractAutoGenerateData(lastBotMessage.text) : null;
  const handleDeleteSuggestion = (savedAt: string) => {
  deleteLocalDoc(savedAt); // utils/localSavedDocs.ts에 정의된 함수
  const savedReports = loadLocalReports();
  const buttons = savedReports.map((r) => {
    const name = templateNameMap[r.templateType] ?? r.templateType;
    return {
      label: `📄 ${name} (${r.savedAt})`,
      savedAt: r.savedAt,
    };
  });

  setMessages((prev) => {
    const lastBot = prev[prev.length - 1];
    if (lastBot.sender === 'bot' && lastBot.type === 'suggest') {
      const updated = [...prev];
      updated[updated.length - 1] = {
        ...lastBot,
        options: buttons,
      };
      return updated;
    }
    return prev;
  });
};

  return (
    <div className="flex flex-col h-[calc(85vh-4rem)]">
      <div className="flex justify-between items-center px-4 pt-4">
        <h2 className="text-xl font-bold">법률 상담</h2>
        <button onClick={handleReset} className="text-sm text-gray-500 hover:text-red-600 underline">
          Chatbot 초기화
        </button>
      </div>

      <div className="flex-1 overflow-y-auto rounded shadow-inner p-4 space-y-5 bg-no-repeat bg-center bg-contain"
        style={{ backgroundImage: `url('/chat_background_lawmate.png')`, backgroundSize: '50%' }}>

        <div className="mb-6 text-center">
          <img src="/ai_law_icon_lawmate.png" alt="AI 법률 상담" className="mx-auto h-28 mb-4" />
          <h3 className="text-xl font-bold">AI 법률 상담 시작하기</h3>
          <p className="text-gray-600 mt-2">어떤 법적 문제를 겪고 계신가요? 아래에 입력해 주세요.</p>

          <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4 text-sm text-gray-700">
            <div className="bg-white p-4 rounded shadow text-center">
              <strong className="block font-bold mb-1">법률 문서 작성 지원</strong>
              계약서, 합의서, 고소장까지 필요한 문서를 손쉽게 작성하세요.
            </div>
            <div className="bg-white p-4 rounded shadow text-center">
              <strong className="block font-bold mb-1">법률 상담 및 조언</strong>
              궁금한 법률 문제, LawMate가 빠르게 상담해 드립니다.
            </div>
            <div className="bg-white p-4 rounded shadow text-center">
              <strong className="block font-bold mb-1">문서 템플릿 추천</strong>
              상황에 맞는 최적의 템플릿을 추천해드립니다.
            </div>
            <div className="bg-white p-4 rounded shadow text-center">
              <strong className="block font-bold mb-1">리스크 분석 가이드</strong>
              문서 속 리스크와 수정 방향을 안내합니다.
            </div>
          </div>
        </div>

        {messages.filter((msg) => msg.text.trim() !== '' || msg.text === '__typing__').map((msg, idx) => (
          <ChatBubble
            key={idx}
            sender={msg.sender}
            text={msg.text}
            type={msg.type}
            options={msg.options}
            timestamp={msg.timestamp}
            onSelectSuggestion={handleSelectSuggestion}
            onDeleteSuggestion={handleDeleteSuggestion}
          />
        ))}

        {autoGenerateData && (
          <div className="text-center mt-6">
            <button className="px-6 py-2 bg-blue-600 text-white font-semibold rounded hover:bg-blue-700 transition"
              onClick={() => navigate('/edit', { state: autoGenerateData })}>
              ✍️ 자동 문서 작성하기
            </button>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <div className="border-t bg-white p-3 shadow-inner">
        <ChatInput onSend={handleSend} disabled={loading} inputRef={inputRef} />
      </div>
    </div>
  );
};

export default ChatbotPage;
