export interface AutoGenerateTrigger {
  templateName: string;
  templateType: string;
  variables: Record<string, string>;
}

const templateMap: Record<string, string> = {
  '내용증명': 'CONTENT_PROOF',
  '고소장(명예훼손)': 'DEFAMATION_REPORT',
  '지급명령 이의신청서': 'PAYMENT_OBJECTION',
  '부동산 임대차 계약서': 'LEASE_CONTRACT',
  '유언장': 'WILL_DOCUMENT',
  '근로계약서': 'EMPLOYMENT_CONTRACT',
  '금전차용증': 'LOAN_AGREEMENT',
};

export function extractAutoGenerateData(text: string): AutoGenerateTrigger | null {
  const templateMatch = text.match(/이제\s*\[?([^\[\]\n]+)\]?\s*문서 작성 모드로 전환/);
  const templateName = templateMatch?.[1];

  const jsonMatch = text.match(/```json\s*(\{[\s\S]*?})\s*```/) || text.match(/(\{[\s\S]*})/);
  const jsonBlock = jsonMatch?.[1];

  if (!templateName || !jsonBlock) return null;

  const templateType = templateMap[templateName.trim()];
  if (!templateType) return null;

  try {
    const variables = JSON.parse(jsonBlock);
    return { templateName: templateName.trim(), templateType, variables };
  } catch {
    return null;
  }
}
